#include<iostream.h>
void main()
{
	int i,j,a[4][4],sum=0;
	cout<<"请输入16个数"<<endl;
	for(i=0;i<4;i++)
			for(j=0;j<4;j++)			
			{
			  cin>>a[i][j];
		      if(i==j) 
			 sum+=a[i][j];
			}
		 cout<<"主对角线元素之和sum="<<sum<<endl;
     for(j=1;j<4;j++)
	{
		for(i=0;i<j;i++)
			a[i][j]=a[i][j]+1;
	}
	for(i=1;i<4;i++)
	{
		for(j=0;j<i;j++)
			a[i][j]=a[i][j]-1;
	}
	for(i=0;i<4;i++)
	{
		for(j=0;j<4;j++)
		{
			cout<<a[i][j]<<"\t";
		}
		cout<<endl;
	}
}